FROM public.ecr.aws/lambda/python:3.9

# Copy requirements and source code
COPY requirements-lambda.txt ./requirements.txt
COPY main.py ${LAMBDA_TASK_ROOT}
COPY src/ ${LAMBDA_TASK_ROOT}/src/

# Install dependencies
RUN pip install -r requirements.txt --target ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler
CMD ["main.lambda_handler"]